[package]
name = "lambert_izzo_wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "WASM bindings for the lambert_izzo solver"
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lambert_izzo = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
tsify = { workspace = true, features = ["js"] }
wasm-bindgen.workspace = true

[dev-dependencies]
lambert_izzo_test_support = { workspace = true }
